services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - .env
    #volumes:
      #- .:/var/www/html
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - app-network

  db:
    image: 'mysql/mysql-server:8.0'
    ports:
        - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
    #volumes:
     # - db_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - app-network

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    command: php artisan schedule:work
    env_file:
      - .env
    #volumes:
     # - .:/var/www/html
    depends_on:
      - db
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local