name: Dusk Tests (Extended)

on:
  push:
    branches:
      - develop
    paths:
      - 'app/**'
      - 'tests/Browser/**'
      - 'tests/DuskTestCase.php'
      - 'database/**'
      - 'resources/**'
      - 'routes/**'
      - 'composer.json'
      - 'composer.lock'
      - 'package.json'
      - 'package-lock.json'
      - 'vite.config.js'
      - '.env.dusk.ci'
      - '.github/workflows/test-dusk-extended.yml'

  pull_request:
    branches:
      - develop
    paths:
      # The tests themselves have changed
      - 'tests/Browser/**'
      # The test configurations has changed
      - '.env.dusk.ci'
      # The action itself has changed
      - '.github/workflows/test-dusk-extended.yml'

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  dusk-extended:
    runs-on: ubuntu-latest
    name: Run Extended Dusk Tests
    env:
      APP_URL: 'http://127.0.0.1:8000'
      DB_USERNAME: root
      DB_PASSWORD: root
      MAIL_MAILER: log

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, dom, fileinfo, mysql

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare The Environment
        run: cp .env.dusk.ci .env

      - name: Create Database
        run: |
          sudo systemctl start mysql
          mysql --user="root" --password="root" -e "CREATE DATABASE \`yaffa\` character set UTF8mb4 collate utf8mb4_bin;"

      - name: Install Composer Dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Upgrade Chrome Driver
        run: php artisan dusk:chrome-driver --detect

      - name: Start Chrome Driver
        run: ./vendor/laravel/dusk/bin/chromedriver-linux --port=9515 >/dev/null 2>&1 &

      - name: Cache NPM Dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install NPM Dependencies
        run: npm ci

      - name: Build Assets
        run: npm run build

      - name: Run Laravel Server
        run: php artisan serve --no-reload &

      - name: Run Extended Dusk Tests
        run: php artisan dusk --group=extended

      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: dusk-extended-screenshots
          path: tests/Browser/screenshots

      - name: Upload Console Logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: dusk-extended-console
          path: tests/Browser/console
